name = "registro-devandalos-proxy"
main = "_worker.js"
compatibility_date = "2026-08-31"

[env.production]
routes = [
  { pattern = "registrodevandalos.pages.dev/api/*", zone_name = "registrodevandalos.pages.dev" }
]

# Variable de entorno para el backend
[vars]
BACKEND_URL = "http://192.168.100.23:8005"
